### ISSUE TITLE
Duplicate anomalies pushed to Elasticsearch

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#60] opened 2018-10-22 12:09 UTC
I am seeing duplicate anomaly entries being written to Elasticsearch:
```
[
    {
        "_index": "ml-my-sine-wave-2",
        "_type": "doc",
        "_id": "rgagm2YBtFE6FUhu_0xd",
        "_score": 3.9267395,
        "_source": {
            "lower_value": -1.1230436942770323,
            "is_anomaly": true,
            "score": 43.94052888607426,
            "upper_value": -0.7867065288827582,
            "@timestamp": 1540209300000,
            "value": -0.954875111579895
        }
    },
    {
        "_index": "ml-my-sine-wave-2",
        "_type": "doc",
        "_id": "tAahm2YBtFE6FUhuJkzb",
        "_score": 3.5902672,
        "_source": {
            "lower_value": -1.1230436942770323,
            "is_anomaly": true,
            "score": 43.94052888607426,
            "upper_value": -0.7867065288827582,
            "@timestamp": 1540209300000,
            "value": -0.954875111579895
        }
    }
]
```

I expected to have only one entry per anomaly detected. The logs from the Loud ML instance are a bit confusing as it seems to be checking a much wider range than the bucket interval:
```
INFO:root:job[dfc03aa4-a9ca-42ea-a60c-9e1e08fb51f1] starting
INFO:root:setting threshold range min=25.700082 max=40.886495
INFO:root:forecast(ml-my-sine-wave-2) range=2018-10-22T12:02:05.000Z-2018-10-22T12:02:55.000Z
INFO:root:extracting data for range=2018-10-22T12:01:15.000Z-2018-10-22T12:02:55.000Z
INFO:root:connecting to elasticsearch on 192.168.0.1:9200
INFO:root:found 20 time periods
INFO:root:generating forecast
INFO:root:forecast(ml-my-sine-wave-2) range=2018-10-22T12:02:05.000Z-2018-10-22T12:03:00.000Z
INFO:root:extracting data for range=2018-10-22T12:01:15.000Z-2018-10-22T12:03:00.000Z
INFO:root:found 21 time periods
INFO:root:generating forecast
INFO:root:forecast(ml-my-sine-wave-2) range=2018-10-22T12:02:05.000Z-2018-10-22T12:03:05.000Z
INFO:root:extracting data for range=2018-10-22T12:01:15.000Z-2018-10-22T12:03:05.000Z
INFO:root:found 22 time periods
INFO:root:generating forecast
INFO:root:job[dfc03aa4-a9ca-42ea-a60c-9e1e08fb51f1] predicted values for 3 time buckets
WARNING:root:detected anomaly for model 'ml-my-sine-wave-2' at 2018-10-22T12:02:55.000Z (score = 45.8)
WARNING:root:anomaly still in progress for model 'ml-my-sine-wave-2' at 2018-10-22T12:03:00.000Z (score = 49.0)
INFO:root:commit 3 change(s) to elasticsearch
INFO:root:job[dfc03aa4-a9ca-42ea-a60c-9e1e08fb51f1] done
```

The model is as follows:
```
{
    "settings": {
        "bucket_interval": "5s",
        "default_datasource": "sine_wave",
        "features": [
            {
                "anomaly_type": "low_high",
                "field": "value",
                "metric": "avg",
                "name": "value"
            }
        ],
        "grace_period": 0,
        "interval": 10,
        "max_evals": 50,
        "max_threshold": 0,
        "min_threshold": 0,
        "name": "ml-my-sine-wave-2",
        "offset": 10,
        "run": {
            "detect_anomalies": true,
            "save_prediction": true
        },
        "seasonality": {
            "daytime": false,
            "weekday": false
        },
        "span": 10,
        "timestamp_field": "@timestamp",
        "type": "timeseries"
    },
    "state": {
        "loss": 0.0045575396044679846,
        "trained": true
    },
    "training": {
        "job_id": "b658de03-eb77-4111-a956-7650881ddc08",
        "progress": {
            "eval": 51,
            "max_evals": 50
        },
        "state": "done"
    }
}
```

**Comment by regel** [comment] 2018-10-25 06:46
Hi @daradermody, some highlights:

- Your interval is 10s, so loudmld will wake-up every 10s to run inference and write the output to the DB
- It seems that there is 1 anomaly in progress. In this situation the range of data points will be larger than 10s since live data is unreliable, a larger time window is used automatically.

Do you notice these duplicates only during anomalies, or in other situations too?

**Comment by daradermody** [comment] 2018-10-25 12:01
There seem to be periodic duplicates independent of any anomalies in progress. See below for a graph showing the aggregation of source signal, predictions (expected, upper and lower), and anomalies (in red), and the counts of predictions pushed to Elasticsearch by Loud ML. It seems like duplicates appear every 10 seconds.

![image](https://user-images.githubusercontent.com/7104356/47498728-048df780-d856-11e8-85bb-a202272ec386.png)

I also created a model for a signal with 1s interval, and it still produced a duplicate every 10 seconds:

![image](https://user-images.githubusercontent.com/7104356/47496862-0fde2480-d850-11e8-9157-13a1b2175a95.png)

**Comment by regel** [comment] 2018-10-31 16:51
Hi @daradermody, ok bug reproduced.

**Comment by wooyey** [comment] 2020-05-12 11:03
Just wondering Sebastien if you are interested in quick fix of this bug as well?
It's here for a long time ... but it could be fixed quite easy. At least I think so.

**Comment by wooyey** [comment] 2020-05-13 15:45
Hey @regel!
What you think about such approach? 
It's a little bit "hackish" and won't work if data differs (e.g. score value) for same timestamp. Still do the job for duplicated data as is in the ticket.

**Comment by regel** [comment] 2020-05-13 20:04
Hey @wooyey ! I love it. This is genius. PR merged.

**Closed** 2020-05-15 05:27 UTC
Labels: bug
